### ISSUE TITLE
require': cannot load such file -- Win32API (LoadError)

### ISSUE THREAD

**Issue by adokitkat** [kaitai-io/kaitai_struct_visualizer#63] opened 2024-08-07 21:48 UTC
I get this error using Windows 11 and installation using `gem`:

```text
ksv .\partition_decrypted.bin .\nvs.ksy

Compilation OK
... processing .\nvs.ksy 0
Error: [{"file"=>"./nvs.ksy", "path"=>[], "message"=>".\\nvs.ksy (The system cannot find the file specified)"}]
Fatal errors encountered, cannot continue
PS C:\Users\Adam> cd .\Downloads\nvs
PS C:\Users\Adam\Downloads\nvs> ksv .\partition_decrypted.bin .\nvs.ksy
Compilation OK
... processing .\nvs.ksy 0
...... loading nvs.rb
Classes loaded OK, main class = Nvs
<internal:C:/Ruby33-x64/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require': cannot load such file -- Win32API (LoadError)
Did you mean?  win32/sspi
        from <internal:C:/Ruby33-x64/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/kaitai-struct-visualizer-0.7/lib/kaitai/console_windows.rb:2:in `<top (required)>'
        from <internal:C:/Ruby33-x64/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
        from <internal:C:/Ruby33-x64/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/kaitai-struct-visualizer-0.7/lib/kaitai/tui.rb:14:in `initialize'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/kaitai-struct-visualizer-0.7/lib/kaitai/struct/visualizer/visualizer.rb:15:in `new'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/kaitai-struct-visualizer-0.7/lib/kaitai/struct/visualizer/visualizer.rb:15:in `run'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/kaitai-struct-visualizer-0.7/bin/ksv:53:in `<top (required)>'
        from C:/Ruby33-x64/bin/ksv:32:in `load'
        from C:/Ruby33-x64/bin/ksv:32:in `<main>'
```

**Comment by generalmimon** [comment] 2024-08-07 22:01
@adokitkat Thanks for reporting. This has been fixed on the [`master` branch](https://github.com/kaitai-io/kaitai_struct_visualizer/tree/master) (see https://github.com/kaitai-io/kaitai_struct_visualizer/issues/48), but unfortunately has not been released [at RubyGems](https://rubygems.org/gems/kaitai-struct-visualizer) yet.

In the meantime, please clone this repo and run the `bin/ksv` script directly, like explained in https://github.com/kaitai-io/kaitai_struct_visualizer/issues/48#issuecomment-1503294039:

> Running `ksv` from source code without installing it using RubyGems first is easy - just instead of running `ksv` (installed as a global command), you run [`bin/ksv`](https://github.com/kaitai-io/kaitai_struct_visualizer/blob/78f7ac22210d3a59c1593a785d58bd2d86f8e1fc/bin/ksv) in the cloned https://github.com/kaitai-io/kaitai_struct_visualizer repository. It's ready to be run like this (even when it's not installed in the usual directory where RubyGems installs packages and scripts).

**Comment by generalmimon** [comment] 2024-08-07 22:01
Duplicate of #48

**Closed by generalmimon** 2024-08-07 22:01 UTC
Labels: bug, duplicate
